server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=restaurants
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false